# Generated by Django 5.2 on 2025-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
