# Generated by Django 5.2 on 2025-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta')], max_length=3)),
                ('disciplina', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('sala', models.CharField(max_length=500)),
                ('cor_sala', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
    ]
