# Generated by Django 5.2 on 2025-04-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('PPT', 'Apresentação PowerPoint'), ('ZIP', 'Arquivo Compactado'), ('VID', 'Vídeo'), ('DOC', 'Documento'), ('LNK', 'Link Externo')], max_length=3)),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('is_novo', models.BooleanField(default=True)),
                ('disciplina', models.CharField(max_length=100)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='usuarios.aula')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'ordering': ['-data_upload'],
            },
        ),
    ]
