# Generated by Django 5.2 on 2025-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('icone', models.CharField(default='fa-bullhorn', max_length=50)),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
