# Generated by Django 5.2 on 2025-04-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_eventoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EVENTO', 'Evento'), ('PALESTRA', 'Palestra'), ('COMPETICAO', 'Competição'), ('REUNIAO', 'Reunião'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
