# Generated by Django 5.2 on 2025-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_eventogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('nome_professor', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('atendimento', models.CharField(max_length=100)),
            ],
        ),
    ]
