# Generated by Django 5.2 on 2025-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_contatoprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
